### ISSUE TITLE
...

### ISSUE THREAD

**Issue by Barnac1ed** [Ireadycoder/iReady-OverLoad-update#1]
you kinda straight up stole this from cupidity & didn't credit him or even change it

**Comment by Ireadycoder** [comment]
he got it rom arjan i gave him credit.

**Comment by Barnac1ed** [comment]
well, it's all cupidty's original work now cus it's entirely different from arjan's since arjan's got patched. it's on similarity is the format of the extension, but the hack itself isn't arjan's.

**Comment by Barnac1ed** [comment]
not only that but u changed like 3 things in the readme, it's almost entirely a ripoff of cupidity's lol

**Comment by Ireadycoder** [comment]
im working with the guy on discord ofc its gonna be the same

**Comment by Ireadycoder** [comment]
any menu is gonna have the same code what do you want? a new menu? lmao

**Comment by Pokecraft30pizza1** [comment]
It says that it is outdated?
